version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: study-postgres
    environment:
      POSTGRES_DB: studydb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: study-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: study-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  localstack:
    image: localstack/localstack:latest
    container_name: study-localstack
    env_file:
      - .env
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs,kms
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  pgdata:
